# parser: '@typescript-eslint/parser'

parserOptions:
  project: ./tsconfig.json

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/react
  - prettier/@typescript-eslint

# plugins:
#   - '@typescript-eslint'

env:
  browser: true
  node: true

rules:
  react/state-in-constructor: off
  react/jsx-one-expression-per-line: 2
  '@typescript-eslint/member-delimiter-style': 2
