parser: '@typescript-eslint/parser'

parserOptions:
  project: ./tsconfig.json

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/react
  - prettier/@typescript-eslint
  - plugin:prettier/recommended

plugins:
  - '@typescript-eslint'

env:
  browser: true
  node: true

rules:
  react/state-in-constructor: off
  react/jsx-one-expression-per-line: 2
  '@typescript-eslint/member-delimiter-style': 2
